### ISSUE TITLE
How to decorate Request before is sent?

### ISSUE THREAD

**Issue by gino8080** [hapijs/wreck#128]
Hello,

How can i use the request events to decorate , and add variable headers, to my request before is sent?

this is my code:

```javascript
var Wreck = require('wreck');
Wreck.on("request", function(uri, options){
    options.headers = {
        'SECRET_TOKEN' : createToken(uri,options)
    }

//do I have to return something
//or these options are automatically added to the original request?
})

var createToken = function(uri, options){ 
  //super secret stuff :)    
    return token;
}

WreckRequest.get("http://endpoint.com/"
                {}, //is ok to pass empty?
                function(err, response, payload) {
console.log(payload)
});
```

**Comment by geek** [comment]
At this point the `uri` will be whats used for the headers in the request.  Its the object that will be passed into the node core request function.  I will update the documentation so that this is clear.

Here is an example of how to set a header using the new request event:

https://github.com/hapijs/wreck/blob/master/test/index.js#L2193-L2221

**Comment by gino8080** [comment]
ok solved :)

I had to decorate the uri and NOT the options like this:
```javascript
var Wreck = require('wreck');
Wreck.on("request", function(uri, options){
    uri.headers = {
        'SECRET_TOKEN' : createToken(uri,options)
    }
//this is the correct way! :)
})


```

**Comment by gino8080** [comment]
ops sorry did not refreshed the page

thank you @geek !
