### ISSUE TITLE
Difference between .request and convenience methods .get, .post, etc.

### ISSUE THREAD

**Issue by 03byron** [hapijs/wreck#214]
I just found a difference in the error handling of `.request` and its convenience methods. I wanted to ask if this behavior is intended or if i can try to provide a fix for this?

For example:
`Wreck.get('http://someapi.com/notFoundEndpoint');`
and 
`Wreck.request('get', 'http://someapi.com/notFoundEndpoint');`

When http://someapi.com/notFoundEndpoint responses with a statusCode >= 400, `.get` would reject, request would just resolve.

**Comment by geek** [comment]
@03byron this is intentional. The shortcut methods make a couple of assumptions, like that they should read the response body for you and that they should also return errors if there is a 400+ status. It wasn't always this way, but people who are using the shortcut methods preferred the auto error behavior that you see now. In order to keep everyone else happy, the request method doesn't make this assumption.

**Comment by 03byron** [comment]
Thanks for your explanation, @geek.
