### ISSUE TITLE
How to handle HTTP_PROXY with Wreck

### ISSUE THREAD

**Issue by SachaCR** [hapijs/wreck#64]
We need to pass through proxy for our http(s) calls.

request npm use by default envrionment variables HTTP_PROXY, HTTPS_PROXY, NO_PROXY
Is there a way to configure that with wreck ?

At the moment we use with success global-tunnel npm but he did'nt provide the no_proxy feature.

**Comment by achingbrain** [comment]
Proxy support would be very useful. I'm trying (read: failing) to port some code from [request](https://libraries.io/npm/request) to Wreck but we're required to go through a proxy in our environments.

**Comment by hueniverse** [comment]
Supporting all the request features in wreck will turn it into the swamp request is... I still think this is better served by another module that builds on top of wreck.

**Comment by tuxtitlan** [comment]
@SachaCR would you mind to share the code that you used with global-tunnel?

**Comment by Kikketer** [comment]
The problem I have is that I'm expanding a vendor application that depends > depends > depends on this project.  The corporate proxy is standing in the way of the application building and I don't have control over the dependencies that this vendor product has.

Somewhat unrelated, but is there a way to easily inject a different dependency in a situation like this?  It seems like no, since you wouldn't want people to inject their own libraries where you were expecting the original.

**Comment by geek** [comment]
@Kikketer I am happy to incorporate this change into the project. It depends on a member of the community to contribute a pull request with the enhancement.

**Comment by mrlannigan** [comment]
I believe this might work for you:
* https://www.npmjs.com/package/http-proxy-agent
* or https://www.npmjs.com/package/https-proxy-agent

```javascript
const Wreck = require('wreck');
const HttpProxyAgent = require('http-proxy-agent');
const proxy = process.env.http_proxy || 'http://127.0.0.1:3128'; // this is placeholder logic
const agent = new HttpProxyAgent(proxy);

const wreck = Wreck.defaults({
    agent
});
```

**Comment by Kikketer** [comment]
@mrlannigan Thanks for the suggestion, but the issue lies in the fact that the npm install step and "build" step all take place on the build box (which is largely out of my control).

I'm building Kibana, which in turn depends on Wreck to download NodeJS binaries (since it builds for different environments).  The build box simply does `npm install` with the proxy settings setup as environment variables.

Then after it finishes the install it runs the build step, which during it's process uses Wreck to download NodeJS.  All I can alter is the environment variables since I don't want to mess with Kibana's build steps (fearing merge and breaking future changes by the Kibana team).

I could alter the package.json of Kibana and change Wreck to be something else (even a fork?).  The package.json file would be manageable to deal with merges and the like.

**Comment by geek** [comment]
@Kikketer it may be easier to submit an update to wreck ;)

**Comment by Kikketer** [comment]
@geek Hehe maybe.  For now I just did a minor update to their build script similar to what @mrlannigan had posted.  It actually wasn't too bad, but I still worry about mucking around in their build scripts.  Another solution may be to suggest the change I did to Kibana instead of this project.

Thanks for all your help.  We can probably close this one now.

**Comment by nlf** [comment]
i think this one can also probably be documented and closed, the http(s)-proxy-agent modules do a fine job in my experience

**Comment by Kikketer** [comment]
Yeah the http-proxy-agent worked I just had to fork the dependency.  It's just unfortunate that I had to do that (and I assume some people can't do that).

**Comment by tuananh** [comment]
A bit troublesome in my opinion while `request` respect `HTTP_PROXY` environment variable and just works.
